// <auto-generated />
namespace DLL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class addedproductseed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedproductseed));
        
        string IMigrationMetadata.Id
        {
            get { return "201911121216415_added-product-seed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
