// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace ECommerce.DLL.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class addedorderLines : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedorderLines));
        
        string IMigrationMetadata.Id
        {
            get { return "201911121021550_added-orderLines"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
