// <auto-generated />
namespace ECommerce.DLL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class fixcategoryparentid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixcategoryparentid));
        
        string IMigrationMetadata.Id
        {
            get { return "201911221621254_fix-category-parent-id"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
