// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace ECommerce.DLL.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class addedtrackingnumbertocart : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedtrackingnumbertocart));
        
        string IMigrationMetadata.Id
        {
            get { return "201911150917532_added-tracking-number-to-cart"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
